### ISSUE TITLE
double free or corruption (!prev) with avx2

### ISSUE THREAD

**Issue by wwww-wwww** [veluca93/fpnge#13]
![test2](https://user-images.githubusercontent.com/19401176/179460602-e099d191-24e4-4817-9109-8c85609e12ca.png)

[imagedata.zip](https://github.com/veluca93/fpnge/files/9130128/imagedata.zip)
width 460
height 460
num_channels 4
bytes_per_channel 1

**Comment by animetosho** [comment]
Ack, looks like I messed up the alignment code.

You can fix this by changing the following line in fpnge.cc:

	std::vector<unsigned char> pdata_buf(bytes_per_line_buf);

and replacing it with

	std::vector<unsigned char> pdata_buf(bytes_per_line_buf + SIMD_WIDTH - 1);

Thanks for reporting!
