### ISSUE TITLE
[fjxld] group tiles by type, then decode using SIMD

### ISSUE THREAD

**Issue by alantudyk** [veluca93/fpnge#26]
Hi, Luca.

The question is related to jxl.

Previously I noticed that decoder is 10 times slower than encoder: https://github.com/libjxl/libjxl/pull/1975#issuecomment-1416775973

I guess, it is because of dependency between pixels at decoding. What if to group tiles with the same predictor type?

I said "guess" because I'm unable to locate the code for encoding and decoding `-e 1`, the structure of `libjxl` is a bit over-complicated. Can you provide the direct links at current `master`?

Or, maybe, you want to test this idea and write `fjxld`?

**Comment by veluca93** [comment]
Moving the discussion to the jxl repo, which is more appropriate :)
