### ISSUE TITLE
Fail to compile on GitHub vs, MSVC

### ISSUE THREAD

**Issue by manticore-projects** [veluca93/fpnge#28]
```
 D:\a\fpng-java\fpng-java\fpnge\src\main\cpp\fpnge.cc(816): error C2416: attribute 'msvc::forceinline' cannot be applied in this context
```

Please refer to: https://github.com/manticore-projects/fpng-java/actions/runs/6925604696/job/18836513239#step:4:106

Can you please help me with this? I have no idea what it means.

**Comment by veluca93** [comment]
Interesting... Can you try replacing line 25 (`#define FORCE_INLINE_LAMBDA
[[msvc::forceinline]]`) with (`#define FORCE_INLINE_LAMBDA`)? That should
solve the issue.

**Comment by manticore-projects** [comment]
Thank you very much, this has worked and FPNGE built on Windows with MVCC.
We have a Java Wrapper now with native 64-bit binaries for Linux, Windows and MacOS included: https://github.com/manticore-projects/fpng-java

All published to Maven.
Thank you a lot for your help and cheers!
